### PR TITLE
Make transmission settings configurable and move static install to docke…

### PR DESCRIPTION
**Pull request by dza89**

### CODE REVIEW

**Comment by dza89** [comment]
I need to do some more testing.

**Comment by dza89** [comment]
Testing done.

**Comment by dza89** [comment]
@SebDanielsson 

Had got time to check this?
Summary:
- Moved the theme to the Dockerfile since that static and is unnecessary to do in the entrypoint
- Made some minor changes to reduce the amount of layers
- Made an additional which grabs all env vars starting with TRANSMISSION_ and applies them to the settings.json
   The if else on 39-48 is necessary to diff between strings and ints.

**Comment by SebDanielsson** [comment]
Sorry for being so slow to respond. The changes look good. Since I'm still very new to Docker feel free to send in any additional impovents. Maybe we could S6 to move away from running as root?

**Pull request merged**
